### ISSUE TITLE
Vitamins (Iron, Zinc, etc) use is prevented by Oak

### ISSUE THREAD

**Issue by Dark-Dragon** [tehkrizz/Krizz-Kaizo-IronMon#1]
Trying to use any of those is met with Oaks "This isn't the time to use that"-text.

**Comment by tehkrizz** [comment]
I'll have a release with this fixed out this afternoon.

**Comment by tehkrizz** [comment]
New release fixes this.
https://github.com/tehkrizz/Krizz-Kaizo-IronMon/releases/tag/v0.5.1
