### ISSUE TITLE
PP restoring items are usable outside of combat

### ISSUE THREAD

**Issue by Dark-Dragon** [tehkrizz/Krizz-Kaizo-IronMon#2]
Elixirs, ethers as well as Leppa berries are usable outside of combat, despite Kaizo rules prohibiting it.

**Comment by tehkrizz** [comment]
I have this fixed, but I'm going to hold off on release for now in case something else is found.

**Comment by Dark-Dragon** [comment]
That's fair, I'm actively looking for stuff at the moment and reporting stuff as I find it.

**Comment by tehkrizz** [comment]
Fixed in https://github.com/tehkrizz/Krizz-Kaizo-IronMon/releases/tag/v0.6
