### ISSUE TITLE
Starter can be Slaking

### ISSUE THREAD

**Issue by Dark-Dragon** [tehkrizz/Krizz-Kaizo-IronMon#3]
Slaking (670 BST) can be received as a starting Pokemon, when the "only legal starting Pokemon"-clause should catch anything outside of the <=599 BST bounds.

**Comment by tehkrizz** [comment]
Logic corrected. Pending testing and release.

**Comment by tehkrizz** [comment]
Fixed in https://github.com/tehkrizz/Krizz-Kaizo-IronMon/releases/tag/v0.6
