### ISSUE TITLE
Can receive multiple items from mom

### ISSUE THREAD

**Issue by Dark-Dragon** [tehkrizz/Krizz-Kaizo-IronMon#5]
If you keep pressing A at the right time while mom warps you out, you can receive a second item during the transition.

**Comment by tehkrizz** [comment]
Did you confirm the item is in your inventory? I have a check in that's supposed to prevent it.

**Comment by Dark-Dragon** [comment]
Yup they're definitely both there.

**Comment by tehkrizz** [comment]
Ugh, ok. I'll take another look.

**Comment by tehkrizz** [comment]
The existing check was trash. I have a new one that should work to test.

**Comment by tehkrizz** [comment]
Fixed in https://github.com/tehkrizz/Krizz-Kaizo-IronMon/releases/tag/v0.6
