### ISSUE TITLE
Double battles can act funky with multi-targeting moves

### ISSUE THREAD

**Issue by Dark-Dragon** [tehkrizz/Krizz-Kaizo-IronMon#6]
Rather than trying to explain this in much detail I'll just share [this twitch VOD](https://www.twitch.tv/videos/1812448407). In short, after a hit with water spout the placeholder pokemon started showing its name plate and the game seemed to be very unsure about what HP my pokemon should be at, correcting it multiple times on hits.

**Comment by tehkrizz** [comment]
This is a known issue. It doesn't actually impact anything, just a visual thing.

**Comment by Dark-Dragon** [comment]
Are you sure? According to the tracker I left the battle with 145 HP after being hit with super fang and multiple other moves. Now unfortunately I went to heal right after, not checking in-game, but wouldn't the tracker's display the correct value? Or was it just the dummy that got hit?

**Comment by tehkrizz** [comment]
I did a good bit of testing of double battles to verify. Your fight was longer than pretty much all of my double battles though. If you can check in game HP, that would be helpful. I don't want to trust the tracker on this one considering how buggy it is. All of my tests I checked in game. 

Edit: I'm also going to start another test run, but not sure when I'll get that far in it.

**Comment by Dark-Dragon** [comment]
I'll close this issue for now and re-open it if I can confirm any unintended behavior during another battle.
